### ISSUE TITLE
Nothing gets sent, no errors

### ISSUE THREAD

**Issue by wastedige** [SparkPost/csharp-sparkpost#31] opened 2016-04-11 16:33 UTC
I have API keys, SPF and DKIM set up, have SparkPost 1.0.7 package from NuGet and I'm using this code to send mail:
```
            var transmission = new Transmission();
            transmission.Content.From.Email = "no-reply@xyz.comn";
            transmission.Content.From.Name = "xyzInquiry";
            transmission.Content.Subject = "xyzwebsite inquiry form";
            transmission.Content.Text = textContent;
            transmission.Content.Html = htmlContent;
            transmission.Content.ReplyTo = inquiry.Email;

            var recipient = new Recipient
            {
                Address = new Address { Email = CloudConfigurationManager.GetSetting("ContactFormMailbox") }
            };
            transmission.Recipients.Add(recipient);
            var sparkPost = new Client(CloudConfigurationManager.GetSetting("SparkPostApiKey"));
            var result = sparkPost.Transmissions.Send(transmission);
```

When I send mail, I receive no error yet nothing gets sent. Doing a breakpoint for result variable suggests the following:

>  Id = 27, Status = RanToCompletion 

However I get this when I intentionally throw an exception with the result variable, underneath the send line:

>  Id = 31, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}" System.Threading.Tasks.Task<SparkPost.SendTransmissionResponse>

**Comment by darrencauthon** [comment] 2016-04-11 20:15
Hello @wastedige 

Can you add the line at the bottom of this, and see if that helps?

```c#
var result = sparkPost.Transmissions.Send(transmission);
result.Wait();
```

I wonder if the ```Wait()``` method call is enough?  I just played with it a little bit in a console app, and it only seemed to send when I put that call in at the bottom.

**Comment by awright18** [comment] 2016-04-11 20:43
Is this async code? If it is you probably need an async method modifier. Also if you are in a MVC or Web API controller you may need to inherit from AsyncController.

**Comment by darrencauthon** [comment] 2016-04-11 20:46
This is async code, it's using the standard ```HttpClient``` under the hood.  No fanciness, it's just making http calls.

I don't think you need the async modifier if you call ```Wait()```.

**Comment by nickc73** [comment] 2016-04-12 09:16
I have the same problem. Just installed the Nuget package and created a test method, but nothing seems to be sent, but no errors are received.  Here's my code:

`
   public static void SendViaSparkPost()
        {
var transmission = new Transmission();
            transmission.Content.From.Email = "noreply@siteaddressgoeshere.com"; 
            transmission.Content.Subject = "Oh hey!";
            transmission.Content.Text = "Testing SparkPost - the world\'s most awesomest email service!";
            transmission.Content.Html = "test content";

            var recipient = new Recipient
            {
                Address = new Address { Email = "nick@myemailaddressgoeshere.com" }
            };
            transmission.Recipients.Add(recipient);

            var client = new Client("SparkPostAPIKey".AppSetting());

            try
            {
                client.Transmissions.Send(transmission);
               
            }
            catch (Exception ex)
            {
                Console.Write(ex.Message);
            }
}`

If you've got any ideas - I'd love to hear them!

**Comment by darrencauthon** [comment] 2016-04-12 11:52
@nickc73 Did you try the suggestion above? To either tack on .Wait() or check for async?

The library returns a Task, not the final result. The code still has to be executed, this is the way the .Net Async works.

**Comment by nickc73** [comment] 2016-04-12 12:53
Ah, I had tried it - and it still didn't work - until I double checked my reports on SparkPost and spotted a mis-typed email address!  It does work! Thanks for helping.

**Comment by darrencauthon** [comment] 2016-04-12 14:13
Thank you @nickc73 , glad it works!

@wastedige I've tested the sample code from the readme in Linqpad, a brand-new console app, and... in a working application.  It all seems to be working fine, so I'm going to close this ticket.  But if you are still having problems, please feel free to post the information here and I'll do what I can to help you.

I'm pretty sure it's just a matter of either calling ```Wait()``` or making your method ```async```.  I was able to reproduce your issue... I think.... by not doing those things, and I was able to fix them with ```Wait()```.

**Closed by darrencauthon** 2016-04-12 14:13 UTC

**Comment by wastedige** [comment] 2016-04-12 16:47
@darrencauthon Thanks for following up!

When I add result.wait() under the 'send' line it just never makes it past that line. Then I tried making the method async and adding await at the beginning of send line, in which case the code goes through.

It's probably a good idea to mention this at the Readme file example :)

**Comment by darrencauthon** [comment] 2016-04-12 17:13
@wastedige You are correct, I will do so. :smile:

**Comment by darrencauthon** [comment] 2016-04-12 17:40
@wastedige Updated the readme.  Thank you for bringing this up so we can help other people using the library!  

:clap: :clap: :clap:

**Comment by darrencauthon** [comment] 2016-04-27 15:06
@wastedige Version 1.3.0 has just been released with sync support.

Details here: https://github.com/SparkPost/csharp-sparkpost#special-note-about-async
